### ISSUE TITLE
Port to discord bot

### ISSUE THREAD

**Issue by lipho** [anherrera/acro-python#1]

**Comment by lipho** [comment]
gooby pls.

**Comment by anherrera** [comment]
I need to work on the word lists. There are way too many obscure words, also some of the verbs/adverbs seem to be the wrong part of speech so some of the acros don't make sense.

**Comment by anherrera** [comment]
Ghastlier Ocelot Obstructively Bones You

**Comment by lipho** [comment]
Sounds like a post-rock band.
